-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 14:57:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wemove
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wemove`;

-- -----------------------------------------------------
-- Schema wemove
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wemove`;
USE `wemove`;

-- -----------------------------------------------------
-- Table `wemove`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`member`;

CREATE TABLE IF NOT EXISTS `wemove`.`member`
(
    `id`        INT          NOT NULL AUTO_INCREMENT,
    `gender`    TINYINT      NULL,
    `firstname` VARCHAR(50)  NOT NULL,
    `lastname`  VARCHAR(50)  NOT NULL,
    `email`     VARCHAR(150) NOT NULL,
    `address`   VARCHAR(150) NULL,
    `phone`     VARCHAR(25)  NULL,
    `picture`   BLOB         NULL COMMENT '\n',
    `active`    TINYINT      NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wemove`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`subscription`;

CREATE TABLE IF NOT EXISTS `wemove`.`subscription`
(
    `id`     INT         NOT NULL AUTO_INCREMENT,
    `name`   VARCHAR(50) NOT NULL,
    `price`  INT         NOT NULL,
    `active` TINYINT     NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wemove`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`entry`;

CREATE TABLE IF NOT EXISTS `wemove`.`entry`
(
    `id`        INT      NOT NULL AUTO_INCREMENT,
    `memberid`  INT      NOT NULL,
    `entrytime` DATETIME NOT NULL,
    `leavetime` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_member_entry`
        FOREIGN KEY (`memberid`)
            REFERENCES `wemove`.`member` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_subscription_idx` ON `wemove`.`entry` (`memberid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `wemove`.`member_subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`member_subscription`;

CREATE TABLE IF NOT EXISTS `wemove`.`member_subscription`
(
    `id`             INT  NOT NULL,
    `memberid`       INT  NOT NULL,
    `subscriptionid` INT  NOT NULL,
    `startdate`      DATE NOT NULL,
    `paid`           INT  NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_member`
        FOREIGN KEY (`memberid`)
            REFERENCES `wemove`.`member` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_subscription`
        FOREIGN KEY (`subscriptionid`)
            REFERENCES `wemove`.`subscription` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_member_subscription_1_idx` ON `wemove`.`member_subscription` (`memberid` ASC) VISIBLE;

CREATE INDEX `fk_subscription_idx` ON `wemove`.`member_subscription` (`subscriptionid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `wemove`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`Role`;

CREATE TABLE IF NOT EXISTS `wemove`.`Role`
(
    `id`   INT         NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wemove`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemove`.`staff`;

CREATE TABLE IF NOT EXISTS `wemove`.`staff`
(
    `id`        INT          NOT NULL AUTO_INCREMENT,
    `gender`    TINYINT      NULL,
    `firstname` VARCHAR(50)  NOT NULL,
    `lastname`  VARCHAR(50)  NOT NULL,
    `email`     VARCHAR(150) NOT NULL,
    `address`   VARCHAR(150) NOT NULL,
    `phone`     VARCHAR(25)  NOT NULL,
    `picture`   BLOB         NOT NULL COMMENT '\n',
    `roleid`    INT          NOT NULL,
    `active`    TINYINT      NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_staff_1`
        FOREIGN KEY (`roleid`)
            REFERENCES `wemove`.`Role` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_staff_1_idx` ON `wemove`.`staff` (`roleid` ASC) VISIBLE;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
